language: python

sudo: false

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
  - DJANGO_VERSION=dev

matrix:
  allow_failures:
    - env: DJANGO_VERSION=dev

before_install:
    - pip install sphinx

# command to install dependencies
install:
    - pip install tox

# command to run tests
script:
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION::3},docs
